name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
          
      - name: Git config
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build
        run: pnpm build
        
      - name: Verify build artifacts
        run: |
          if [ ! -f "dist/omnivox-optimizer.user.js" ] || [ ! -f "dist/omnivox-optimizer.meta.js" ]; then
            echo "Build artifacts are missing!"
            exit 1
          fi
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/omnivox-optimizer.user.js
            dist/omnivox-optimizer.meta.js
          generate_release_notes: true